export const shopCategories = [
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "home", label: "Home & Furniture" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "automotive", label: "Automotive & Accessories" },
  { value: "food", label: "Food & Beverages" },
  { value: "pet", label: "Pet Supplies & Services" },
  { value: "medical", label: "Medical & Pharmacy" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "florist", label: "Florists & Gift Shops" },
  { value: "baby", label: "Baby & Kids Store" },
  { value: "art", label: "Art & Craft Supplies" },
  { value: "music", label: "Music Instruments & Stores" },
  { value: "technology", label: "Software & Technology Services" },
  { value: "garden", label: "Garden & Outdoor Equipment" },
  { value: "bakery", label: "Bakery & Confectionery" },
  { value: "optical", label: "Optical & Eyewear" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "real_estate", label: "Real Estate & Property Services" },
  { value: "fitness", label: "Fitness & Wellness Centers" },
  { value: "entertainment", label: "Entertainment & Gaming" },
  { value: "restaurant", label: "Restaurant & Café" },
  { value: "grocery", label: "Grocery & Supermarket" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "education", label: "Education & Coaching" },
  { value: "photography", label: "Photography & Studio" },
  { value: "travel", label: "Travel & Tourism" },
  { value: "handmade", label: "Handmade & Crafts" },
  { value: "printing", label: "Printing & Custom Merchandise" },
  { value: "it_services", label: "IT Services & Development" },
  { value: "consulting", label: "Consulting & Professional Services" },
  { value: "construction", label: "Construction & Renovation" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "logistics", label: "Logistics & Delivery" },
  { value: "events", label: "Event Planning & Management" },
  { value: "gaming", label: "Gaming & Esports" },
  { value: "other", label: "Other" }
];